create table non_bc_residents as
select * from property 
where cityname != 'ASHEVILLE'
AND cityname != 'MILLS RIVER'
AND cityname != 'LEICESTER'
AND cityname != 'AVERY'
AND cityname != 'SWANNANOA'
AND cityname != 'BLACK MOUNTAIN'
AND cityname != 'FAIRVIEW' 
AND cityname != 'FLETCHER' 
AND cityname != 'BILTMANDE FANDEST' 
AND cityname != 'WEAVERVILLE'
AND cityname != 'WOODFIN'
AND cityname != 'MONTREAT'
AND cityname != 'AVERY CREEK'
AND cityname != 'CANDLER'
AND cityname != 'BARNARDSVILLE'
AND cityname != 'FANDKS OF IVY'
AND cityname != 'JUPITER'
AND cityname != 'RIDGECREST'
AND cityname != 'FLAT CREEK'
AND cityname != 'ENKA'
AND cityname != 'ROYAL PINES' 
AND cityname != 'ALEXANDER'
AND cityname != 'ARDEN'
AND cityname != 'SKYLAND'
AND cityname != 'STOCKSVILLE'
AND cityname != 'IVY'
AND cityname != 'SANDY MUSH'
AND cityname != 'HAZEL'
AND cityname != 'LIMESTONE'
AND cityname != 'BLACK MTN'
AND cityname != 'FRENCH BROAD'
AND cityname != 'MONTREAT'
AND cityname != 'BILTMORE FOREST'
and cityname != 'BILTMORE LAKE'
and cityname != 'PISGAH FOREST'


 
